spring:
  config:
    import: optional:file:.env[.properties]

  graphql:
    graphiql:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            provider: google
            scope:
              - email
              - profile
              - openid
            authorization-grant-type: authorization_code
        provider:
          google:
            user-name-attribute: email

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
        mail:
          debug: false
          transport:
            protocol: smtp
          smtp:
            auth: true
            starttls:
              enable: true

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=oranger
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: oranger

  sql:
    init:
      mode: never
      continue-on-error: false

cloudinary:
  cloud_name: ${CLOUD_NAME}
  api_key: ${API_KEY}
  api_secret: ${API_SECRET}

jwt:
  key: ${JWT_KEY}
  jwtAccessExpiration: 10080m #7day
  jwtRefreshExpiration: 131490m #3_month
  jwtUserDataExpiration: 1440m #1day