spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME} #localhost
#    url: jdbc:postgresql://db_backend:5432/marketplace
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always

app:
  cors:
    allowed-origins: http://localhost:3000