spring:
  config:
    import: optional:file:.env[.properties]
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
        mail:
          debug: false
          transport:
            protocol: smtp
          smtp:
            auth: true
            starttls:
              enable: true
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always

app:
  cors:
    allowed-origins: http://localhost:3000

cloudinary:
  cloud_name: ${CLOUD_NAME}
  api_key: ${API_KEY}
  api_secret: ${API_SECRET}

jwt:
  key: ${JWT_KEY}