name: Auto Deploy

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: ./gradlew test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: success()

    steps:
      - name: Trigger Deploy Hook
        run: |
          curl -X POST -d {} ${{ secrets.deployGithub }}
